datasource:
  chronos:
    base:
      jdbcUrl: jdbc:mysql://10.110.9.218:6306/alpine
      username: scheduler_x
      password: 4hI0MZm51P
      poolName: chronos-base-datasource
      maximum-pool-size: 300
      minimum-idle: 50
    support:
      jdbcUrl: jdbc:mysql://10.110.9.218:6306/alpine
      username: scheduler_x
      password: 4hI0MZm51P
      poolName: chronos-support-datasource
      maximum-pool-size: 300
      minimum-idle: 50
#[eureka]
eureka:
  instance:
    metadata-map:
      env: test
  client:
    serviceUrl:
      defaultZone: http://10.110.46.35:1111/eureka/

logging:
  config: classpath:logback/logback-test.xml

chronos:
  server: chronos-server-qzbeta.test.mail.163.com
  appName: mail-common
  password: mail-common
  eventWorkflowId: 5

### 大师号客户端相关配置
master:
  core:
    appId: chronos-portal
    host: http://master-account-core.ns1.qzgw-beta.163.internal
    salt: ZDhhY2Q1MDI1NmUy

auth:
  config:
    allowDisableTimestampCheck: true
    allowDisableSignCheck: true
    allowDisableMasterFpCheck: true