datasource:
  chronos:
    base:
      jdbcUrl: jdbc:mysql://10.110.9.218:6306/alpine
      username: scheduler_x
      password: 4hI0MZm51P
      poolName: chronos-base-datasource
      maxPoolSize: 10
      minIdle: 1
    support:
      jdbcUrl: jdbc:mysql://10.110.9.218:6306/alpine
      username: scheduler_x
      password: 4hI0MZm51P
      poolName: chronos-support-datasource
      maxPoolSize: 10
      minIdle: 1
#[eureka]
eureka:
  instance:
    metadata-map:
      env: test
  client:
    serviceUrl:
      defaultZone: http://10.110.46.35:1111/eureka/

logging:
  config: classpath:logback/logback-test.xml