datasource:
  chronos:
    base:
      jdbcUrl: jdbc:mysql://localhost:3306/alpine?useSSL=false&allowPublicKeyRetrieval=true
      username: Echo009
      password: ironman
      pool-name: chronos-base-datasource
    support:
      jdbcUrl: jdbc:mysql://localhost:3306/alpine?useSSL=false&allowPublicKeyRetrieval=true
      username: Echo009
      password: ironman
      pool-name: chronos-support-datasource




logging:
  config: classpath:logback/logback-local.xml