#[app]
spring:
  profiles:
    active: local
  application:
    name: chronos-portal

#[web server]
server:
  servlet:
    application-display-name: chronos-portal
  port: 18087
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{X-Forwarded-For}i %{User-Agent}i %D'
      directory: /home/tomcat/logs
      file-date-format: .yyyy-MM-dd

management:
  server:
    port: 1101
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'


logging:
  logger:
    app: com.netease.mail

#[eureka]
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true


chronos:
  table:
    prefix: sx_



