server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{X-Forwarded-For}i %D'
      directory: /home/tomcat/logs
  servlet:
    application-display-name: chronos-executor
  port: 18087
spring:
  application:
    name: chronos-executor
  profiles:
    active: local
  jpa:
    open-in-view: false
powerjob:
  worker:
    # Application name, used for grouping applications. Recommend to set the same value as project name.
    app-name: mail-common


management:
  server:
    port: 1101
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: /admin
      exposure:
        include: '*'

logging:
  logger:
    app: com.netease.mail

#[eureka]
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: true


chronos:
  table:
    prefix: sx_
